import { Product } from "@/types/woocommerce";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 17,
    name: "Cemento Comodoro PCR - Bolsa 50kg",
    slug: "cemento-comodoro-pcr-50kg",
    permalink: "#",
    price: "8990",
    regular_price: "9990",
    sale_price: "8990",
    on_sale: true,
    stock_status: "instock",
    images: [{ id: 1, src: "/images/comodoro-2000.png", name: "Cemento Comodoro", alt: "Bolsa de Cemento Comodoro" }],
    categories: [{ id: 1, name: "Construcción", slug: "construccion" }],
    sku: "CM-PCR-50",
    description: "Cemento Portland de alta resistencia, ideal para estructuras de hormigón armado y obras civiles en la Patagonia Chilena. Formulación especial para climas extremos.",
    short_description: "Solidez certificada para proyectos en Magallanes.",
    attributes: []
  },
  {
    id: 205,
    name: "Silla Nordik Oak - Edición Limitada",
    slug: "silla-nordik-oak",
    permalink: "#",
    price: "45000",
    regular_price: "59900",
    sale_price: "45000",
    on_sale: true,
    stock_status: "instock",
    images: [{ id: 4, src: "/images/luxury-home.webp", name: "Silla Nordik", alt: "Silla de roble estilo nórdico" }],
    categories: [{ id: 2, name: "Muebles", slug: "muebles" }],
    sku: "MU-NK-OK",
    description: "Silla de diseño contemporáneo fabricada en roble sólido. Perfecta para ambientes que buscan el 'Quiet Luxury'.",
    short_description: "Elegancia y confort para tu hogar.",
    attributes: []
  },
  {
    id: 103,
    name: "Porcelanato Antártico 60x120 - Rectificado",
    slug: "porcelanato-antartico-60x120",
    permalink: "#",
    price: "22900",
    regular_price: "27500",
    sale_price: "22900",
    on_sale: true,
    stock_status: "instock",
    images: [{ id: 3, src: "/images/industrial-pro.webp", name: "Porcelanato Antartico", alt: "Porcelanato rectificado 60x120" }],
    categories: [{ id: 3, name: "Revestimientos", slug: "revestimientos" }],
    sku: "PORC-ANT-120",
    description: "Porcelanato de gran formato con acabado mate antideslizante. Ideal para zonas de alto tráfico en la Patagonia.",
    short_description: "Superficies de alto desempeño estético.",
    attributes: []
  },
  {
    id: 301,
    name: "Escritorio Magallanes Industrial",
    slug: "escritorio-magallanes-industrial",
    permalink: "#",
    price: "125000",
    regular_price: "125000",
    sale_price: "",
    on_sale: false,
    stock_status: "instock",
    images: [{ id: 5, src: "/images/industrial-pro.webp", name: "Escritorio Magallanes", alt: "Escritorio industrial" }],
    categories: [{ id: 2, name: "Muebles", slug: "muebles" }],
    sku: "MU-ESC-MAG",
    description: "Escritorio robusto con base de acero y cubierta de madera nativa recuperada.",
    short_description: "Fuerza y diseño en tu espacio de trabajo.",
    attributes: []
  }
];
