import { Product } from "@/types/woocommerce";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 17,
    name: "Cemento Comodoro PCR - Bolsa 50kg",
    slug: "cemento-comodoro-pcr-50kg",
    permalink: "#",
    price: "8990",
    regular_price: "9990",
    sale_price: "8990",
    on_sale: true,
    stock_status: "instock",
    images: [{ id: 1, src: "/images/comodoro-2000.png", name: "Cemento Comodoro", alt: "Bolsa de Cemento Comodoro" }],
    categories: [{ id: 1, name: "Construcción", slug: "construccion" }],
    sku: "CM-PCR-50",
    description: "Cemento Portland de alta resistencia, ideal para estructuras de hormigón armado y obras civiles en la Patagonia Chilena. Formulación especial para climas extremos.",
    short_description: "Solidez certificada para proyectos en Magallanes.",
    attributes: []
  },
  {
    id: 205,
    name: "Cocina Modular Premium - Serie 2026",
    slug: "cocina-modular-premium",
    permalink: "#",
    price: "450000",
    regular_price: "599000",
    sale_price: "450000",
    on_sale: true,
    stock_status: "instock",
    images: [{ id: 4, src: "/images/showcase-cocina.png", name: "Cocina Premium", alt: "Cocina modular moderna" }],
    categories: [{ id: 2, name: "Cocina", slug: "cocina" }],
    sku: "CO-MOD-26",
    description: "Sistema de cocina modular con acabados premium y herrajes de cierre suave. Diseño optimizado para espacios modernos.",
    short_description: "Elegancia y funcionalidad en tu cocina.",
    attributes: []
  },
  {
    id: 103,
    name: "Cerámica Gres Patagonia 60x60",
    slug: "ceramica-gres-patagonia-60x60",
    permalink: "#",
    price: "18900",
    regular_price: "24500",
    sale_price: "18900",
    on_sale: true,
    stock_status: "instock",
    images: [{ id: 3, src: "/images/home-ceramicas.png", name: "Cerámica Patagonia", alt: "Cerámica gres 60x60" }],
    categories: [{ id: 3, name: "Cerámicas", slug: "ceramicas" }],
    sku: "CER-GRES-60",
    description: "Cerámica de alta resistencia ideal para interiores y exteriores en zonas frías.",
    short_description: "Resistencia y estética regional.",
    attributes: []
  },
  {
    id: 301,
    name: "Aislante Térmico Wool-Pro 50mm",
    slug: "aislante-termico-wool-pro-50mm",
    permalink: "#",
    price: "32000",
    regular_price: "32000",
    sale_price: "",
    on_sale: false,
    stock_status: "instock",
    images: [{ id: 5, src: "/images/home-aislante.png", name: "Aislante Wool-Pro", alt: "Rollo aislante térmico" }],
    categories: [{ id: 4, name: "Aislación", slug: "aislacion" }],
    sku: "AIS-WP-50",
    description: "Aislante térmico de fibra mineral de alto desempeño. Barrera térmica definitiva para la Patagonia.",
    short_description: "Eficiencia térmica de nivel industrial.",
    attributes: []
  }
];
